[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.2.1"
async-graphql-axum = "7.2.1"
axum = "0.8.8"
rstest = "0.26.1"
tokio =  { version = "1.49.0", features = ["full"] }
